### ISSUE TITLE
Affirmation for correctly answered exercises

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri-exercise-perseus-plugin#43]
Answering an exercise correctly doesn't give indication of 'Correct' in the button.  Instead, the button shows 'Next Question'.

Vodafone Foundation finds it desireable for a form of affirmation for correct exercises.

**Comment by 66eli77** [comment]
@khang do you have any ideas for this?

**Comment by khangmach** [comment]
Indication of correct answer: 

change hex color to Next Question button to #43A047 green
set transition of current color (#3A3A3A) to the color above to maybe 1.2s so that there is some delay while the learner searches for some indication of their success or incorrect submission

Indication of wrong answer:

error text of color #DF0F0F below the attempt spaces:  _ _ _ 
have the error text be within the white box containing those spaces, directly above the "check answer" button
